/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WinPregunta.java
 *
 * Created on 18-ago-2010, 21:03:12
 */
package segmcolor;

/**
 *
 * @author Hector Rattis
 */
public class WinPregunta extends javax.swing.JFrame {

    private Lienzo lienzo;
    private int idzona;

    /** Creates new form WinPregunta */
    public WinPregunta(Lienzo l, int idZona) {
        lienzo = l;
        idzona = idZona;
        initComponents();
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nmedio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ntercio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ncuarto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nsexto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        noctavo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ndoceavo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18));
        jLabel1.setText("Cuantas piezas necesitaste para completar el entero:");

        nmedio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nmedio.setText("0");

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14));
        jLabel2.setText("<html> Tipo de <br> pieza :</html>");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/frac_medio.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Serif", 1, 12));
        jLabel4.setText("<html> Número<br> de piezas :</html>");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/frac_tercio.png"))); // NOI18N

        ntercio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ntercio.setText("0");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/frac_cuarto.png"))); // NOI18N

        ncuarto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ncuarto.setText("0");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/frac_sexto.png"))); // NOI18N

        nsexto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nsexto.setText("0");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/frac_octavo.png"))); // NOI18N

        noctavo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        noctavo.setText("0");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/frac_doceavo.png"))); // NOI18N

        ndoceavo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ndoceavo.setText("0");

        jButton1.setText("Comprobar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nmedio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(ntercio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(ncuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(nsexto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(noctavo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(ndoceavo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jButton1)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nmedio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ntercio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ncuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nsexto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noctavo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ndoceavo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            this.getClass().getMethod(lienzo.getZonas().get(idzona).getClase()).invoke(this, (Object[]) null);

        } catch (Exception ex) {
            System.out.println("NO INVOKE!!" + ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField ncuarto;
    private javax.swing.JTextField ndoceavo;
    private javax.swing.JTextField nmedio;
    private javax.swing.JTextField noctavo;
    private javax.swing.JTextField nsexto;
    private javax.swing.JTextField ntercio;
    // End of variables declaration//GEN-END:variables

    public void Medio() {
        if (nmedio.getText().equals(new String("2"))) {
            new VentanaAnuncio().anuncioEntero("!Muy bien!¡Así se hace!");
            lienzo.removePiezas(idzona);
            lienzo.getZonas().get(idzona).resetSetEnteros();
            this.dispose();
        } else {
            new VentanaAnuncio().anuncioEntero("Prueba de nuevo");
        }
    }

    public void Tercio() {
        if (ntercio.getText().equals(new String("3"))) {
            new VentanaAnuncio().anuncioEntero("!Muy bien!¡Así se hace!");
            lienzo.removePiezas(idzona);
            lienzo.getZonas().get(idzona).resetSetEnteros();
            this.dispose();
        } else {
            new VentanaAnuncio().anuncioEntero("Prueba de nuevo");
        }
    }

    public void Cuarto() {
        if (ncuarto.getText().equals(new String("4"))) {
            new VentanaAnuncio().anuncioEntero("!Muy bien!¡Así se hace!");
            lienzo.removePiezas(idzona);
            lienzo.getZonas().get(idzona).resetSetEnteros();
            this.dispose();
        } else {
            new VentanaAnuncio().anuncioEntero("Prueba de nuevo");
        }
    }

    public void Sexto() {
        if (nsexto.getText().equals(new String("6"))) {
            new VentanaAnuncio().anuncioEntero("!Muy bien!¡Así se hace!");
            lienzo.removePiezas(idzona);
            lienzo.getZonas().get(idzona).resetSetEnteros();
            this.dispose();
        } else {
            new VentanaAnuncio().anuncioEntero("Prueba de nuevo");
        }
    }

    public void Octavo() {
        if (noctavo.getText().equals(new String("8"))) {
            new VentanaAnuncio().anuncioEntero("!Muy bien!¡Así se hace!");
            lienzo.removePiezas(idzona);
            lienzo.getZonas().get(idzona).resetSetEnteros();
            this.dispose();
        } else {
            new VentanaAnuncio().anuncioEntero("Prueba de nuevo");
        }
    }

    public void Doceavo() {
        if (ndoceavo.getText().equals(new String("12"))) {
            new VentanaAnuncio().anuncioEntero("!Muy bien!¡Así se hace!");
            lienzo.removePiezas(idzona);
            lienzo.getZonas().get(idzona).resetSetEnteros();
            this.dispose();
        } else {
            new VentanaAnuncio().anuncioEntero("Prueba de nuevo");
        }
    }
}
